remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Clase de Matemáticas Discretas]
description: [Este repositorio contiene los temas vistos en un primer curso de Discretas]
show_downloads: true
